#name, main, version and api are required
name: GameSelector
main: GameSelector\Main
version: 0.1
api: 1.13.1
author: EmreTr1
description: GameSelector 
commands:
 gs:
   description: GameSelector
   